# -*- coding: utf-8 -*-
"""LVADSUSR145.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNeW4O7oHoXRFyz5yWyGtR-kztftTIyJ
"""

import pandas as pd
df=pd.read_csv('/content/winequality-red.csv')

df.head()

#no categorical cols
df.isnull().sum()

df.shape

df.dropna(how='any',axis=0)

df.dropna(inplace=True)

df.isnull().sum()

df.shape

df.corr()

plt.figure(figsize=(10,5))
sns.heatmap(df.corr(),annot=True)

#imp feature-alchol,volatile acidity,sulphates

import matplotlib.pyplot as plt
import seaborn as sns
for col in df.columns:
  plt.figure(figsize=(10,5))
  sns.boxplot(df[col])

#outliers:
#interquartile range iq1,iq3=quartile(0.75) iqr=iq3-iq1 then remove
#or by seeing boxplt

#no cat cols so no encoding required

df.duplicated().sum()

df.drop_duplicates()

df.columns

from sklearn.model_selection import train_test_split

#target variable=quality
X=df.drop('quality',axis='columns')
y=df['quality']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=110)

#scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()
clf.fit(X_train_scaled,y_train)
y_pred=clf.predict(X_test_scaled)

from sklearn.metrics import accuracy_score,precision_score,recall_score
print('Accuracy_score:',accuracy_score(y_test,y_pred))

print('Precision_score:',precision_score(y_test,y_pred))
print('Recall_score:',recall_score(y_test,y_pred))