# -*- coding: utf-8 -*-
"""LVADSUSR145_Kotha_Brinda_Vivek_IA1_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXTEJg5QvomKIhYNr9IpjbyWC9yXj33C
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix,r2_score,mean_squared_error,accuracy_score,f1_score,precision_score,recall_score
from sklearn.feature_selection import RFE

df=pd.read_csv('/content/booking.csv')

df

df.info()

df.describe(include="all")

df.isnull().sum()

df.drop('room type',axis=1)

df.drop('average price',axis=1)

#encoding
for column in df.columns:
    if df[column].dtype == 'object':
        if column != 'BookingID':
            df[column] = LabelEncoder().fit_transform(df[column])

df

X=df.drop(['booking status'],axis=1)
y=df['booking status']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.30, random_state = 110, stratify=y)

#scaling
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#logistic model
model = LogisticRegression()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)
conf_matrix = confusion_matrix(y_test, y_pred)
conf_matrix

#metrics to measure
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
f1_score = f1_score(y_test, y_pred)
print("Accuracy:",accuracy)
print("Recall:",recall)
print("Precision:",precision)
print("F1_score:",f1_score)

