# -*- coding: utf-8 -*-
"""LVADSUSR145_Kotha Brinda_Vivek_lab4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RKUpvi0Ek96jTx-J1CYDsjnhumIYOYNm

**KOTHA BRINDA VIVEK**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#import dataset
df=pd.read_csv('/content/anomaly_train.csv')

df.head()

df.isnull().sum()

df.dropna(axis=0,inplace=True)

df.duplicated().sum()

df.drop_duplicates()

df.info()

df.describe(include="all")

#outliers:
num_cols=df.select_dtypes(include=['int64','float64'])
corr_mat=num_cols.corr()
plt.figure(figsize=(10,5))
sns.heatmap(corr_mat,annot=True)

"""almost all are independent features(no high correlation with each other ,so need to remove features with high correlation in this anomaly detection)"""

#outliers analysis but should not removove outliers for anomaly detection:
#if any outliers:
for c in num_cols:
  plt.figure(figsize=(10,5))
  sns.boxplot(df[c])

df.columns

from sklearn.preprocessing import LabelEncoder
lab_e=LabelEncoder()
cat_col=df.select_dtypes(include=('object')).columns
for c in cat_col:
  df[c]=lab_e.fit_transform(df[c])

selected_features=['Amount','Type','Time','Location','User']
selected_features_df = df[selected_features]
from sklearn.ensemble import IsolationForest
isolation_forest = IsolationForest(n_estimators=100,contamination=0.1, random_state=42)
isolation_forest.fit(selected_features_df)

y_pred = isolation_forest.predict(selected_features_df)
df["anomaly_score"] = isolation_forest.decision_function(selected_features_df)
anomalies = df.loc[df["anomaly_score"] < 0]
y_pred

df

#replacing 0 and 1 with yes and no for anomalies
df['anomaly'] = np.where(y_pred == 1, 'no', 'yes')
plt.scatter(df["Amount"], df["anomaly_score"], label="Normal")
plt.scatter(anomalies["Amount"], anomalies["anomaly_score"], label="Anomaly")
plt.xlabel("Amount")
plt.ylabel("Anomaly_score")
plt.legend()
plt.show()

#anomalies here are detected when users are transtioning less amount than normal or regular patterns